language: node_js
node_js:
  - "8"

addons:
    apt:
        packages:
            - sshpass


after_success:
    - export SSHPASS=$PASSWORD
    - sshpass -e scp -o stricthostkeychecking=no deploy.sh $USER@$PUBLIC_URL:$DEPLOY_PATH
    - mkdir build
    - mv * build
    - tar -czf package.tgz build
    - sshpass -e scp -o stricthostkeychecking=no package.tgz $USER@$PUBLIC_URL:$DEPLOY_PATH
    - sshpass -e ssh -o stricthostkeychecking=no $USER@$PUBLIC_URL chmod +x $DEPLOY_PATH/deploy.sh
    - sshpass -e ssh -o stricthostkeychecking=no $USER@$PUBLIC_URL $DEPLOY_PATH/deploy.sh

cache:
  directories:
    - "node_modules"